# Generated by Django 4.0.5 on 2022-06-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_coupon_product_total_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
